name: Python package

on: [pull_request]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Unittest
        run: tox -e unittest-'py{37,38,39,310}'
      - name: Coverage
        run: tox -e coverage-'py{37,38,39,310}'
      - name: Linting
        run: tox -e pylint-'py{37,38,39,310}'

